with_spaces = hello   # with_spaces has many spaces after "hello"
after = $(with_spaces)there

nullstring =
space = $(nullstring) #make a variable with a single space

all:
	echo "$(after)"
	echo start"$(space)"end